---
apiVersion: v1
kind: Secret
metadata:
  name: somesecret
  labels:
    quarks.cloudfoundry.org/deployment-name: "cfo-test-deployment"
  annotations:
    quarks.cloudfoundry.org/provides: '{"name":"quarks_gora","type":"quarks-gora"}'
stringData:
  link: |
    quarks-gora.ssl: false
    quarks-gora.port: "1234"
    text_message: admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: "cfo-test-deployment"
  annotations:
    quarks.cloudfoundry.org/link-provider-name: quarks_gora
  name: svcexternal
spec:
  type: ExternalName
  externalName: test.example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: cf-operator-testing-manifest
stringData:
  manifest: |
    ---
    releases:
    - name: quarks-gora
      version: "0.0.9"
      url: docker.io/cfcontainerization
      stemcell:
        os: SLE_15_SP1-26.6
        version: 7.0.0_374.gb8e8e6af
    instance_groups:
    - name: quarks-gora
      instances: 2
      lifecycle: errand
      jobs:
      - name: smoke-tests
        release: quarks-gora
        consumes:
          quarks_gora: {from: quarks_gora}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: cfo-test-deployment
spec:
  manifest:
    name: cf-operator-testing-manifest
    type: secret
